import { useContext, useEffect, useState } from "react";
import './bots.css'
import { CurrentContext } from "../../../context/themeContext";
let cont = 0

export default function ContentBots({apostas}){
    const {girarCarousel, histDados, refresh, setRefresh} = useContext(CurrentContext)
    const [apostasLocal, setApostas] = useState(apostas);
    const nomes = [
        "Conta no Orkut",
        "Nu Sertão",
        "SóXanaEAgua",
        "SawMasBom",
        "Dapra20comer",
        "NinguémJooga",
        "TatyComendo",
        "Tokagando",
        "Uhpapaichegou",
        "Intez Tino",
        "Cruizcredo",
        "Flamengolol",
        "Lord fralda",
        "SeuVagem",
        "Avestruz que te seduz",
        "Ouro que reluz",
        "Melado de óleo",
        "Tentei Comer quem leu",
        "Beijosmeliga",
        "Headshot grátis",
        "Sem Bala",
        "CertouMiseravi",
        "Naum Amola",
        "Cavalo amigável",
        "Morreu antes de ler",
        "100Nome",
        "TudoSpam",
        "Kharne Greylhada",
        "Sniper Boleto",
        "Capa Nera",
        "BatataSozinha",
        "FeraSokeRuim",
        "Amortyzador",
        "Parcyal Mente",
        "VlogImundo",
        "MortoComoFace",
        "After Eita",
        "Erro 504",
        "PuleiMorri",
        "iRuim 2.0",
        "LaggandoD+",
        "LixoDeQualidade",
        "Pirarucu Seboso",
        "MeusProbrema",
        "NickO Riginal",
        "ArsenalFunkeiro",
        "Rato Atomico",
        "Bispo Pelado",
        "Pablo Escovando",
        "Byata R3zando",
        "Cabo Nero",
        "Bruxopolis",
        "Sou1abismo",
        "Adaptoide",
        "DiegoDanger",
        "Dildo Baggins",
        "Riddickulo",
        "Vinho de Diezel",
        "Ze Morteiro",
        "Juan Casavelha",
        "Sayan Casual",
        "MineirodeChernobil",
        "Rick Jaimes",
        "Tirona Lapela",
        "JovemMistico",
        "Urso Vago",
        "MonkeeFeice",
        "Major Morte",
        "Tone Yorke",
        "Fredo Mercurio",
        "Davyd Boyeae",
        "Ivete Comgalo",
        "Eilish Rijinha",
        "Atom JobineAce",
        "Adonis",
        "Badboy",
        "Bam Bam",
        "Bear",
        "Beast",
        "Beef",
        "Biggie",
        "Boner",
        "Boss",
        "Cowboy",
        "Daddy",
        "Elmo",
        "Gasoline",
        "Gangster",
        "Gizmo",
        "Godzilla",
        "Grandpa",
        "Grasshopper",
        "Handsome",
        "Harvard",
        "Hero",
        "Hercules",
        "Hollywood",
        "Hoss",
        "Hunk",
        "Jedi",
        "Macho",
        "Mayhem",
        "Motown",
        "Monster",
        "Moose",
        "Muscle",
        "Nemo",
        "Pickle",
        "Player",
        "Poker",
        "Pooh",
        "Pops",
        "Prince",
        "Pup",
        "Rockstar",
        "Romeo",
        "Scooter",
        "Skipper",
        "Sparkie",
        "Superfly",
        "Teddy",
        "Tiger",
        "Train",
        "Turtle",
        "Vegas",
        "Waldo",
        "Winner",
        "Cachorrão",
        "Gustavo da 12",
        "AnaChe",
        "Gironda",
        "Melissagata",
        "Aquidisgraça",
        "Martaonde",
        "Severinnis",
        "Diegostore",
        "LucasLucão",
        "Armigoonline",
        "Catlucia",
        "Tonymarrento",
        "Deuonda",
        "Metira",
        "Akinori",
        "Thor",
        "Maximus",
        "Exterminator",
        "Overtaker",
        "Naoki",
        "Sniper",
        "RockyBalboa",
        "Jaguar",
        "Torpedo",
        "Hazzard",
        "Satoshi",
        "Scorpion",
        "Mcgregor",
        "Cobra",
        "Falcão",
        "Prodigy",
        "Zombie",
        "Napoleon",
        "Coyote",
        "Rocks",
        "Whiskey",
        "CRMessi",
        "Go cu",
        "Painkiller",
        "Leon",
        "Kitsune",
        "Massacry",
        "Goblete",
        "TurboSquat",
        "HangLoose",
        "Mainframe",
        "CyberMancer",
        "Flint",
        "Pehkonen",
        "Sir Mavros",
        "PointlessShot",
        "Salty BR",
        "PanzerLow",
        "TrapTok",
        "ScourgeWolf",
        "SkyLord",
        "Drakkoo",
        "Guacanarix",
        "Anaphylaxis",
        "Claverol",
        "Ronak",
        "Thunder Cloak",
        "Nygrum",
        "Alcatrax",
        "Black Lot",
        "Othalium",
        "Onyx Stryker",
        "Braquialys",
        "Crixos",
        "HydroSnake",
        "CTrlAltSNiper",
        "Crassus",
        "Baron Zemek",
        "Rifleman AT",
        "HeatSyka",
        "Ariete Aereo",
        "BlackHearth",
        "Brock Blast",
        "Blood Vessel",
        "IceBerry",
        "Sakano",
        "Ahlkemysta",
        "SuzukiSamurai",
        "Tenso",
        "TreeSensa",
        "TheRAM",
        "Pinkie",
        "Alpina Aster",
        "Magahis",
        "Gale",
        "Nacht",
        "Nebel",
        "GrrrlPowa",
        "Polly Rocket",
        "ValsinhaVeneno",
        "Sara Sahara",
        "MoçaTaDiferente",
        "Cover Girl",
        "Girllirla",
        "NinjaKawai",
        "ByancaNoir",
        "Aguja",
        "Mika",
        "Nathy",
        "BeClare",
        "Maya",
        "Aziza",
        "Ostarha",
        "Labirinto de Pandora",
        "PinaColada",
        "Tempestade de Amor",
        "Sniper do Lar",
        "Girassol",
        "Cheetara",
        "Sheera",
        "Dona Flor",
        "PanificadoraOmega",
        "Menina Ideal",
        "Caramelo",
        "Aurora Aboreal",
        "Debie",
        "Bayssa",
        "Athenas",
        "Isis",
        "Olimpia",
        "Gaia",
        "Eris",
        "Gueidy",
        "Europa",
        "Clyrene",
        "Erika",
        "Javalina",
        "Katana",
        "Katrielly",
        "Themis",
        "Harmonia",
        "Ártemis",
        "RainGurl",
        "DropHottie",
        "Mihano",
        "PukkaPie",
        "IrisAzul",
        "Rosae",
        "Cardi C",
        "StutterBling",
        "R4taZana",
        "Barnacula",
        "BlekKween",
        "Strygga",
        "Razorina",
        "Blinka182",
        "BloodShed",
        "Urtyga",
        "CalfKilla",
        "SteinCastle",
        "CoachWhip",
        "Cypher",
        "Dial Murder",
        "Spectrum",
        "Amon Ka",
        "Moonstar",
        "DarkCyfra",
        "DeathTrap",
        "LifeLyne",
        "Navalha",
        "Foice",
        "Titannia",
        "Britania",
        "Magmana",
        "Dagan",
        "Astrid",
        "Dhova",
        "Draconair",
        "DragumEst",
        "Stillaks",
        "Parthunax",
        "Tigris Unum",
        "Magnus",
        "Albicastrum",
        "Hiborian",
        "Celtibero",
        "Octonumbra",
        "Pyrite",
        "Mholag Bal",
        "Corruptor",
        "Flavis",
        "Slarver",
        "Slayer",
        "Scorch",
        "Mogg",
        "Hunter",
        "Mage",
        "Divine",
        "Arrow",
        "Shiryu",
        "Suprem",
        "Phoenix",
        "Legendary",
        "Instinct",
        "Tears",
        "Envyus",
        "Rising",
        "Immortal",
        "Warlock",
        "ClashforCash",
        "Reaper",
        "Pantheon",
        "Maxthon",
        "Executor",
        "BloodFlare",
        "Summoners",
        "HawkEye",
        "JunkieX",
        "SlothKing",
        "Gutzilla",
        "Yoda",
        "Kanabo",
        "Shekelzak",
        "Hexanorte",
        "SunPrism",
        "Derfenders",
        "BuracoBarro",
        "Takomito",
        "Metamorfo",
        "VenenoTox",
        "BigTurtle",
        "TrollOfc",
        "Goblinskin",
        "HydroBlitz",
        "GaviãoX",
        "Bravox",
        "Superesmalte",
        "LigaLoka",
        "Metanix",
        "DribbleRush",
        "AfroSMH",
        "ForageLeo",
        "CativaCarton",
        "Saracura",
        "DashiPrim",
        "InferBunt",
        "MetroMetro",
        "MelmanDaSelva",
        "Sorveteria",
        "DomYurr",
        "SortimoBeng",
        "Letas Cansadas",
        "Piranhão",
        "Muninn",
        "LeitoVirus",
        "RockPeroxide",
        "SucrilhoPerseguidor",
        "AquaCalliope",
        "Invocaterra",
        "Arigolips"
      ];
    useEffect(() => {
        if (girarCarousel) {
            setApostas([]); // Limpa o estado apostas

            const timeoutId = setTimeout(() => {
                console.log('deve resetar tudo agora', apostasLocal);
                console.log("refresh", refresh);
                setApostas(apostasLocal); // Redefine o estado apostas após 1.5s
            }, 1500); // 1.5 segundos de delay

            // Cleanup do timeout
            return () => clearTimeout(timeoutId);
        }
        
    }, [girarCarousel, apostas]);
    return(
        <div className="container-apostas" >
            { 
                
                apostas.map((item, index) => (
                    <div key={index}>
                        <div className='bot-hist'>
                           <div className="nomes-user">{nomes[Math.floor(Math.random() * 300) + 0]}</div> <h3> R${item}</h3>
                        </div>
                    </div>
                ))
            }
            
        </div>
    )
}